import json

""" """""
Q = """{
    "question":[
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Afrique du Sud","capitale":"Pretoria"},
        {"pays":"Albanie","capitale":"Tirana"},
        {"pays":"Algérie","capitale":"Alger"},
        {"pays":"Allemagne","capitale":"Berlin"},
        {"pays":"Andorre","capitale":"Andorre-la-Vieille"},
        {"pays":"Angola","capitale":"Luanda"},
        {"pays":"Antigua-et-Barbuda","capitale":"Saint John's"},
        {"pays":"Arabie Saoudite","capitale":"Riyad"},
        {"pays":"Argentine","capitale":"Erevan"},
        {"pays":"Australie","capitale":"Canberra"},
        {"pays":"Autriche","capitale":"Vienne"},
        {"pays":"Azerbaïdjan","capitale":"Bakou"},
        {"pays":"Bahamas","capitale":"Nassau"},
        {"pays":"Bangladesh","capitale":"Dacca"},
        {"pays":"Bahreïn","capitale":"Manama"},
        {"pays":"Barbade","capitale":"Bridgetown"},
        {"pays":"Belgique","capitale":"Bruxelles"},
        {"pays":"Belize","capitale":"Belmopan"},
        {"pays":"Bénin","capitale":"Porto-Novo"},
        {"pays":"Bhoutan","capitale":"Thimbu"},
        {"pays":"Biélorussie","capitale":"Minsk"},
        {"pays":"Birmanie","capitale":"Naypyidaw"},

        {"pays":"Bolivie","capitale":"Sucre"},
        {"pays":"Bosnie-Herzégovine","capitale":"Sarajevo"},
        {"pays":"Botswana","capitale":"Gaborone"},
        {"pays":"Brésil","capitale":"Brasilia"},
        {"pays":"Brunei","capitale":"Bandar Seri Begawan"},
        {"pays":"Bulgarie","capitale":"Sofia"},
        {"pays":"Burkina Faso","capitale":"Ouagadougou"},
        {"pays":"Burundi","capitale":"Bujumbura"},
        {"pays":"Cap-Vert","capitale":"Praia"},
        {"pays":"Chili","capitale":"Santiago"},
        {"pays":"Chine","capitale":"Pékin"},
        {"pays":"Chypre","capitale":"Nicosie"},

        {"pays":"Colombie","capitale":"Bogota"},
        {"pays":"Comores","capitale":"Moroni"},
        {"pays":"Congo","capitale":"Brazzaville"},
        {"pays":"Corée du Nord","capitale":"Pyongyang"},
        {"pays":"Corée du Sud","capitale":"Séoul"},
        {"pays":"Costa Rica","capitale":"San José"},
        {"pays":"Côte d'Ivoire","capitale":"Yamoussoukro"},
        {"pays":"Croatie","capitale":"Zagreb"},
        {"pays":"Cuba","capitale":"La Havane"},
        {"pays":"Danemark","capitale":"Copenhague"},
        {"pays":"Djibouti","capitale":"Djibouti"},
        {"pays":"Dominique","capitale":"Roseau"},

        {"pays":"Egypte","capitale":"Le Caire"},
        {"pays":"Emirats Arabes Unis","capitale":"Abu Dhabi"},
        {"pays":"Equateur","capitale":"Quito"},
        {"pays":"Erythrée","capitale":"KAsmara"},
        {"pays":"Espagne","capitale":"Madrid"},
        {"pays":"Estonie","capitale":"Tallinn"},
        {"pays":"Eswatini","capitale":"Mbabane"},
        {"pays":"Etats-Unis","capitale":"Washington"},
        {"pays":"Ethiopie","capitale":"Addis-Abeba"},
        {"pays":"Fidji","capitale":"Suva"},
        {"pays":"Finlande","capitale":"Helsinki"},
        {"pays":"France","capitale":"Paris"},

        {"pays":"Gabon","capitale":"Libreville"}
            ]
        }
"""
"""
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},

        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},

        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},

        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},

        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},

        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},

        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},

        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"},
        {"pays":"Togo","capitale":"Lome"},
        {"pays":"Afghanistan","capitale":"Kaboul"}



    ]
    }
"""
Qs = json.loads(Q)

print(Qs)

with open("les_questions.json","w") as g:
    json.dump(Qs,g,indent=2)